### PR TITLE
Add --zip flags to build command

### PR DESCRIPTION
**Pull request by cezaraugusto**
When users run `npx extension build <path>`, add a few flags related to the distribution package:

* `--zip [boolean]`: whether or not to compress the extension into a ZIP file. Defaults to `false`
* `--zip-source [boolean]`: whether or not to include the source files in the ZIP file. Defaults to `false`
* `--zip-filename <string>`: specify the name of the ZIP file. Defaults to the extension name and version, like `my-ext-name-1.0.0.zip`.

Screenshot 2024-06-06 at 19 57 12

### How to test

1. Have an extension
2. Running `yarn extension build <extension-path> --zip` should generate a zip file from distribution files to `(projectPath)/dist/<browser>/<zip-name>.zip`
3. Running `yarn extension build <extension-path> --zip-source` should generate a zip file from source files to `(projectPath)/dist/<browser>/<zip-name>-source.zip`
4. Running `yarn extension build <extension-path> --zip --zip-filename=my-custom-name` should generate a zip file from distribution files (with custom name) to `(projectPath)/dist/<browser>/<custom-zip-name>.zip`.

### CODE REVIEW

**Comment by OSpoon** [comment]
Hi~ @cezaraugusto, I have verified these distribution package-related flags and confirmed that they are all working as expected. However, when using the `--zip-source` flag, have you considered excluding the `node_modules` directory from the zip file ❓

**Comment by cezaraugusto** [comment]
@OSpoon you're right! Now it only adds files not specified by PR updated. I updated the output as well
Screenshot 2024-06-07 at 12 51 50

**Comment by OSpoon** [comment]
Hi~ @cezaraugusto, I think some further improvement is needed. The current zip file is missing the directory structure of the source. 

image

**Comment by OSpoon** [comment]
LGTM++

Thank you very much for inviting me to review your code. I believe this PR can be merged, and I also find the addition of these flags very useful. 😁

**Review by OSpoon — APPROVED** [review]

**Comment by cezaraugusto** [comment]
Thanks @OSpoon!

**Pull request merged**
